/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./public/**/*.html",
  ],
  safelist: [
    // 動的に生成されるクラスを保護
    'bg-gray-100',
    'min-h-screen',
    'container',
    'mx-auto',
    'px-4',
    'py-8',
    'text-3xl',
    'font-bold',
    'text-gray-800',
    'mb-8',
    'fas',
    'fa-video',
    'mr-2',
    'text-blue-600',
    'bg-white',
    'rounded-lg',
    'shadow-md',
    'p-6',
    'mb-6',
    'text-xl',
    'font-semibold',
    'text-gray-700',
    'mb-4',
    'fa-folder-plus',
    'flex',
    'gap-4',
    'flex-1',
    'border',
    'border-gray-300',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'px-6',
    'py-2',
    'text-white',
    'hover:bg-blue-700',
    'transition-colors',
    'fa-plus',
    'fa-list',
    'space-y-3',
    'text-gray-500',
    'text-center',
    'py-8',
    'fixed',
    'top-4',
    'right-4',
    'hidden',
    'border-l-4',
    'shadow-lg',
    'max-w-sm',
    'items-center',
    'fa-check-circle',
    'text-2xl',
    'mr-3',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
