-- Migration 0007: World & Character Bible (Phase X-2)
-- 
-- ⚠️ DEPRECATED: This migration file is NO-OP (does nothing)
-- 
-- Reason:
-- This file was originally created as "0007_world_character_bible.sql" but conflicts
-- with the existing "0007_add_runs_system.sql" (added earlier on 2025-12-16).
-- 
-- To avoid migration history corruption across environments, we:
-- 1. Keep this file as NO-OP (preserves Git history integrity)
-- 2. Moved the actual schema changes to "0010_world_character_bible.sql"
-- 
-- This approach prevents:
-- - Migration order conflicts
-- - Environment-specific "applied/unapplied" inconsistencies
-- - Git history rewriting (which would break team workflows)
-- 
-- The actual World & Character Bible schema is in:
-- - migrations/0010_world_character_bible.sql (world_settings, project_character_models, scene_character_map)
-- - migrations/0011_add_character_aliases.sql (aliases_json column)
-- 
-- This is intentional technical debt documentation, not a code smell.
-- Date: 2026-01-01
-- Context: Phase X-2 migration numbering conflict resolution

-- NO-OP: This file does nothing to avoid migration conflicts
SELECT 1 WHERE 1=0;
